name: Test And Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
          
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 22

# SEEDING DATABASE FOR FAKE DATA
      - name: Seed MongoDB with test data
        run: |
          mongo localhost:27017/test --eval '
            db.todos.insertMany([
              {title:'Fake Todo 1', description:'This is the todo created by github actions'},
              {title:'Fake Todo 2', description:'This is the todo created by github actions'},
            ]);
          '

# INSTALLING pnpm GLOBALLY
      - name: Install pnpm
        run: npm install -g pnpm

# INSTALLING THE DEP AND BUILDING IT
      - name: Install Dependencies And Build
        run: pnpm run build-prod 

# SETTING UP THE CACHING FOR CYPRESS BINARY
      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

# INSTALLING THE CYPRESS BINARY
      - name: Install Cypress binary
        run: pnpm exec cypress install

# STARTING THE SERVER 
      - name: Start The Server
        run: |
          pnpm run start &       # Run in background
          npx wait-on http://localhost:5000

# RUNNING THE CYPRESS TESTS
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with: 
          wait-on: http://localhost:5000

  deploye:
    needs: cypress-run
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.repository == 'MohammedAslam106/practice-cypress'

    steps:
      - name: Trigger Render Deploy Hook
        run: curl -X GET "$RENDER_DEPLOY_HOOK_URL"
        env:
          RENDER_DEPLOY_HOOK_URL: ${{secrets.RENDER_DEPLOY_HOOK_URL}}
      
      
      
